spring:
  application:
    name: products
server:
  port: 8081

aws:
  integration:
    region: us-east-1
  s3:
    bucket: hodrics-store-bucket-001

dep:
  integration:
    baseUrl: "https://fakestoreapi.com"
