spring:
  application:
    name: products
  profiles:
    active: local
server:
  port: 8081

aws:
  integration:
    region: us-east-1
    localstack-endpoint: http://localhost:4566

dep:
  integration:
    baseUrl: "https://fakestoreapi.com"
